# Generated by Django 4.2.3 on 2023-09-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='home/')),
                ('price', models.FloatField()),
            ],
        ),
    ]
